version: "3"
services:

  postgres:
    restart: always
    image: postgres:latest
    networks:
      - backend
    ports:
      - "5454:5432"

  loader:
    build:
      context: ../lib/loader/

    volumes:
      - ../src/database:/tmp/database

    env_file: .env

    networks:
      - backend

    depends_on:
      - postgres

  api:
    build:
      context: ../src/api
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ../src/api/tech_forum_api:/tmp/api/tech_forum_api
    env_file: .env
    environment:
      - CACHE_TYPE=simple
      - PYTHONPATH=/tmp/api/


networks:
  backend:
